const H = storage.H, C = storage.C, S = storage.S;
C.watchedMark = (p, T, x, y) => { const m = H.board(p, 'watched', x, y, 22, 22, { fill: '#000000', op: 0.6, r: 11, clip: false }); H.icon(m, 'eye', 4, 4, 14, '#FFFFFF', 2.2); };
C.libGrid = (b, T, y0, n = 9, o = {}) => { const w = 112; for (let i = 0; i < n; i++) { const col = i % 3, row = Math.floor(i / 3); const px = 16 + col * (w + 9), py = y0 + row * 214; const p = C.poster(b, T, px, py, w, i, { badge: false }); if (o.watched?.includes(i)) C.watchedMark(p, T, w - 28, 6); const it = C.items[i % 12]; H.text(b, it.t, px, py + 172, { size: 13, weight: 600, color: T.fg, w }); H.text(b, `${it.y} · ${it.k === 'tv' ? 'TV' : 'Movie'}`, px, py + 190, { size: 12, color: T.mutedFg, w }); } };
C.stat = (p, T, x, y, w, label, value, ic) => { const c = H.board(p, 'stat ' + label, x, y, w, 76, { fill: T.muted, r: 16, clip: false }); H.icon(c, ic, 12, 12, 16, T.mutedFg, 2); H.text(c, label, 34, 12, { size: 12, weight: 600, color: T.mutedFg }); H.text(c, value, 12, 36, { size: 24, weight: 700, color: T.fg }); };
const libTop = (b, T, active, o = {}) => { C.largeTitle(b, T, 'Library', { y: 62, right: ['search', 'sliders-horizontal'] }); let cx = 16; [['All', 'layout-grid'], ['Movies', 'film'], ['TV', 'tv'], ['Unwatched', 'eye-off']].forEach(([l, ic], i) => { const c = C.chip(b, T, cx, 118, l, { active: i === active, icon: ic }); cx += c.width + 8; });
  H.text(b, o.count || '485 titles', 16, 170, { size: 13, color: T.mutedFg }); const sort = H.board(b, 'sort', 393 - 16 - 170, 164, 170, 28, { fill: null, clip: false }); H.text(sort, 'Recently added', 0, 4, { size: 14, weight: 600, color: T.fg, w: 130, align: 'right' }); H.icon(sort, 'chevron-down', 140, 5, 18, T.fg, 2); };
S.libraryList = [
  ['Library · grid', (T, x, y) => { const b = C.screen(T, `Library · grid · ${T.name}`, x, y); libTop(b, T, 0); C.libGrid(b, T, 204, 6, { watched: [0, 3, 5] }); C.finish(b, T, { tab: 3 }); return b; }],
  ['Library · list', (T, x, y) => { const b = C.screen(T, `Library · list · ${T.name}`, x, y); libTop(b, T, 0); [0, 3, 9, 5, 11].forEach((n, k) => { const yy = 208 + k * 104; C.poster(b, T, 16, yy, 56, n, { badge: false, noTitle: true, r: 8 }); const it = C.items[n]; H.text(b, it.t, 88, yy + 4, { size: 16, weight: 600, color: T.fg }); H.text(b, `${it.y}  ·  ${it.k === 'tv' ? 'TV show' : 'Movie'}  ·  ★ ${it.r.toFixed(1)}`, 88, yy + 26, { size: 13, color: T.mutedFg }); H.text(b, k % 2 ? 'Watched Mar 2' : 'Not watched', 88, yy + 48, { size: 12, color: T.mutedFg }); if (k % 2) H.icon(b, 'eye', 353, yy + 6, 20, T.mutedFg, 2); H.rect(b, 'divider', 88, yy + 90, 289, 1, T.border); }); C.finish(b, T, { tab: 3 }); return b; }],
  ['Library · filters', (T, x, y) => { const b = C.screen(T, `Library · filters · ${T.name}`, x, y); libTop(b, T, 0); C.libGrid(b, T, 204, 3); const s = C.sheet(b, T, 700, 'Filters');
    H.text(s, 'Genre', 20, 72, { size: 15, weight: 600, color: T.fg }); let cx = 20, cy = 104; [['Action', 0], ['Comedy', 0], ['Drama', 1], ['Sci-Fi', 1], ['Thriller', 0], ['Animation', 0]].forEach(([g, a]) => { const c = C.chip(s, T, cx, cy, g, { active: !!a }); cx += c.width + 8; if (cx > 300) { cx = 20; cy += 42; } });
    H.text(s, 'Year', 20, 196, { size: 15, weight: 600, color: T.fg }); H.text(s, '2010 – 2025', 20, 196, { size: 15, color: T.mutedFg, w: 353, align: 'right' }); H.rect(s, 'track', 20, 236, 353, 4, T.muted, { r: 2 }); H.rect(s, 'range', 120, 236, 200, 4, T.fg, { r: 2 }); H.ellipse(s, 'thumb', 110, 228, 20, 20, T.bg, { stroke: [T.fg, 2] }); H.ellipse(s, 'thumb', 310, 228, 20, 20, T.bg, { stroke: [T.fg, 2] });
    H.text(s, 'Minimum rating', 20, 270, { size: 15, weight: 600, color: T.fg }); H.text(s, '7.0+', 20, 270, { size: 15, color: T.mutedFg, w: 353, align: 'right' }); H.rect(s, 'track', 20, 310, 353, 4, T.muted, { r: 2 }); H.rect(s, 'range', 20, 310, 240, 4, T.fg, { r: 2 }); H.ellipse(s, 'thumb', 250, 302, 20, 20, T.bg, { stroke: [T.fg, 2] });
    H.text(s, 'Watched', 20, 344, { size: 15, weight: 600, color: T.fg }); C.segmented(s, T, 20, 376, 353, ['Any', 'Watched', 'Not watched'], 0);
    C.group(s, T, 20, 436, 353, [{ title: 'Never watched by anyone', sub: 'Admins only: library clean-up', icon: 'eye-off', toggle: false }]);
    C.btn(s, T, 20, 700 - 34 - 52 - 52 - 6, 353, 'Show 142 titles', { h: 52 }); C.btn(s, T, 20, 700 - 34 - 52, 353, 'Reset', { h: 46, v: 'ghost' }); return b; }],
  ['Library · not synced', (T, x, y) => { const b = C.screen(T, `Library · not synced · ${T.name}`, x, y); C.largeTitle(b, T, 'Library', { y: 62 }); S.empty(b, T, { y: 250, icon: 'library', title: 'Your library is empty', body: 'Tipsarr hasn’t imported anything from Jellyfin yet. An admin can run a library sync.', cta: 'Run sync', ctaIcon: 'refresh-cw', ctaW: 160, bodyLines: 3 }); C.finish(b, T, { tab: 3 }); return b; }],
  ['Library · loading', (T, x, y) => { const b = C.screen(T, `Library · loading · ${T.name}`, x, y); C.largeTitle(b, T, 'Library', { y: 62 }); let cx = 16; [50, 76, 60, 96].forEach(w => { S.skel(b, T, cx, 118, w + 24, 34, 17); cx += w + 32; }); for (let i = 0; i < 9; i++) { const col = i % 3, row = Math.floor(i / 3); S.skel(b, T, 16 + col * 121, 204 + row * 200, 112, 168, 10); } C.finish(b, T, { tab: 3 }); return b; }],
  ['Watchlist', (T, x, y) => { const b = C.screen(T, `Watchlist · ${T.name}`, x, y); S.navBar(b, T, 'Watchlist'); C.libGrid(b, T, 112, 6); C.homeIndicator(b, T); return b; }],
  ['Hidden titles', (T, x, y) => { const b = C.screen(T, `Hidden titles · ${T.name}`, x, y); S.navBar(b, T, 'Hidden from suggestions'); H.text(b, 'Titles you marked “not interested”.', 16, 108, { size: 14, color: T.mutedFg }); [4, 6, 9].forEach((n, k) => { const yy = 148 + k * 88; C.poster(b, T, 16, yy, 48, n, { badge: false, noTitle: true, noIcon: true, r: 6 }); H.text(b, C.items[n].t, 78, yy + 14, { size: 16, weight: 500, color: T.fg }); H.text(b, `${C.items[n].y}`, 78, yy + 38, { size: 13, color: T.mutedFg }); C.btn(b, T, 393 - 16 - 84, yy + 20, 84, 'Unhide', { h: 34, size: 14, v: 'secondary' }); H.rect(b, 'divider', 78, yy + 76, 299, 1, T.border); }); C.homeIndicator(b, T); return b; }],
];
const profileHead = (b, T, y) => { const pal = C.pal[3]; H.ellipse(b, 'avatar', 393 / 2 - 44, y, 88, 88, [H.grad([[pal[0], 0], [pal[1], 1]])]); H.text(b, 'A', 393 / 2 - 44, y + 22, { size: 36, weight: 700, color: '#FFFFFF', w: 88, align: 'center' }); H.text(b, 'Alice', 0, y + 102, { size: 26, weight: 700, color: T.fg, w: 393, align: 'center' }); H.text(b, 'Member since Oct 2025  ·  last seen today', 0, y + 136, { size: 13, color: T.mutedFg, w: 393, align: 'center' }); };
S.profileList = [
  ['Profile', (T, x, y) => { const b = C.screen(T, `Profile · ${T.name}`, x, y); C.largeTitle(b, T, 'Profile', { y: 62, right: ['settings', 'users'] }); profileHead(b, T, 118);
    C.stat(b, T, 16, 276, 112, 'Requests', '12', 'list-checks'); C.stat(b, T, 140, 276, 112, 'Watchlist', '8', 'bookmark'); C.stat(b, T, 264, 276, 113, 'Watched', '143', 'eye');
    C.sectionHeader(b, T, 16, 372, 361, 'Recent requests', 'All'); [1, 3, 0].forEach((n, k) => { const yy = 410 + k * 84; C.poster(b, T, 16, yy, 44, n, { badge: false, noTitle: true, noIcon: true, r: 6 }); H.text(b, C.items[n].t, 74, yy + 8, { size: 16, weight: 600, color: T.fg }); const bd = C.badge(b, T, 74, yy + 36, ['requested', 'downloading', 'available'][k], {}); H.rect(b, 'divider', 74, yy + 74, 303, 1, T.border); });
    C.finish(b, T, { tab: 4 }); return b; }],
  ['Settings', (T, x, y) => { const b = C.screen(T, `Settings · ${T.name}`, x, y); S.navBar(b, T, 'Settings');
    H.text(b, 'ACCOUNT', 20, 108, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 130, 361, [{ title: 'Accounts', icon: 'users', value: '3' }, { title: 'Profile picture', icon: 'user' }, { title: 'Language', icon: 'languages', value: 'English' }, { title: 'Region', icon: 'globe', value: 'FR' }, { title: 'Score on posters', icon: 'star', value: 'TMDB' }]);
    H.text(b, 'APPEARANCE', 20, 410, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 432, 361, [{ title: 'Theme', icon: 'palette', value: 'System' }]);
    H.text(b, 'SECURITY', 20, 508, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 530, 361, [{ title: 'Lock with Face ID', icon: 'scan-face', toggle: true }, { title: 'Signed-in devices', icon: 'monitor-smartphone', value: '3' }]);
    H.text(b, 'SERVER', 20, 664, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 686, 361, [{ title: 'tipsarr.brebond.com', sub: 'Tipsarr 0.5.0 · connected', icon: 'server', chev: false }]);
    C.group(b, T, 16, 768, 361, [{ title: 'Sign out', icon: 'log-out', danger: true, chev: false }]); C.homeIndicator(b, T); return b; }],
  ['Theme picker', (T, x, y) => { const b = C.screen(T, `Theme picker · ${T.name}`, x, y); S.navBar(b, T, 'Theme'); const opts = [['System', 'Follows your iPhone', 'smartphone', true], ['Light', '', 'sun', false], ['Dark', '', 'moon', false]]; C.group(b, T, 16, 112, 361, opts.map(o => ({ title: o[0], sub: o[1] || undefined, icon: o[2], chev: false }))); H.icon(b, 'check', 393 - 16 - 14 - 22, 112 + 21, 22, T.fg, 2.4); H.text(b, 'Choose how Tipsarr looks. System follows the appearance set in iOS.', 20, 320, { size: 13, color: T.mutedFg, w: 353, lh: 1.35 }); C.homeIndicator(b, T); return b; }],
  ['Language picker', (T, x, y) => { const b = C.screen(T, `Language picker · ${T.name}`, x, y); S.navBar(b, T, 'Language'); C.group(b, T, 16, 112, 361, [{ title: 'Default (iPhone language)', chev: false }, { title: 'English', chev: false }, { title: 'Français', chev: false }]); H.icon(b, 'check', 393 - 16 - 14 - 22, 112 + 15 + 52, 22, T.fg, 2.4); H.text(b, 'Used for the interface and for titles and descriptions from TMDB.', 20, 290, { size: 13, color: T.mutedFg, w: 353, lh: 1.35 }); C.homeIndicator(b, T); return b; }],
  ['Score on posters', (T, x, y) => { const b = C.screen(T, `Score picker · ${T.name}`, x, y); S.navBar(b, T, 'Score on posters'); C.group(b, T, 16, 112, 361, [{ title: 'TMDB', chev: false }, { title: 'IMDb', sub: 'Movies only', chev: false }, { title: 'Metacritic', sub: 'Movies only', chev: false }, { title: 'Rotten Tomatoes', sub: 'Movies only', chev: false }]); H.icon(b, 'check', 393 - 16 - 14 - 22, 112 + 15, 22, T.fg, 2.4); H.text(b, 'IMDb, Metacritic and Rotten Tomatoes need an admin to set up Radarr; everything else shows TMDB.', 20, 400, { size: 13, color: T.mutedFg, w: 353, lh: 1.35 }); C.homeIndicator(b, T); return b; }],
  ['Signed-in devices', (T, x, y) => { const b = C.screen(T, `Signed-in devices · ${T.name}`, x, y); S.navBar(b, T, 'Signed-in devices'); H.text(b, 'Browsers and apps where you are signed in.', 16, 108, { size: 14, color: T.mutedFg });
    [['iPhone 15 Pro', 'This device · Tipsarr 1.0 · now', 'smartphone', true], ['iPad', 'Tipsarr 1.0 · yesterday', 'monitor-smartphone'], ['Web browser', 'Firefox on Linux · 2 days ago', 'globe']].forEach(([t, sub, ic, cur], k) => { const yy = 140 + k * 80; const card = H.board(b, 'device ' + t, 16, yy, 361, 68, { fill: T.card, r: 16, stroke: [T.border, 1], clip: false }); const ib = H.board(card, 'icon', 14, 18, 32, 32, { fill: T.muted, r: 9, clip: false }); H.icon(ib, ic, 6, 6, 20, T.fg, 1.9); H.text(card, t, 60, 12, { size: 16, weight: 600, color: T.fg }); H.text(card, sub, 60, 36, { size: 13, color: T.mutedFg, w: 250 }); if (!cur) H.icon(card, 'x', 361 - 38, 22, 20, T.mutedFg, 2); });
    C.btn(b, T, 16, 400, 361, 'Sign out everywhere else', { h: 48, v: 'secondary', icon: 'log-out' }); C.homeIndicator(b, T); return b; }],
  ['Face ID lock', (T, x, y) => { const b = C.screen(T, `Face ID lock · ${T.name}`, x, y); S.navBar(b, T, 'Lock with Face ID'); C.group(b, T, 16, 112, 361, [{ title: 'Lock with Face ID', icon: 'scan-face', toggle: true }]); H.text(b, 'LOCK AFTER', 20, 192, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 214, 361, [{ title: 'Immediately', chev: false }, { title: 'After 1 minute', chev: false }, { title: 'After 5 minutes', chev: false }, { title: 'After 15 minutes', chev: false }]); H.icon(b, 'check', 393 - 16 - 14 - 22, 214 + 15 + 52, 22, T.fg, 2.4); H.text(b, 'Tipsarr asks for Face ID when you return to the app after this delay. You stay signed in either way.', 20, 440, { size: 13, color: T.mutedFg, w: 353, lh: 1.35 }); C.homeIndicator(b, T); return b; }],
  ['Sign out confirm', (T, x, y) => { const b = C.screen(T, `Sign out confirm · ${T.name}`, x, y); S.navBar(b, T, 'Settings'); H.rect(b, 'scrim', 0, 0, 393, 852, '#000000', { op: 0.5 }); const g1 = H.board(b, 'action group', 8, 852 - 34 - 170, 377, 106, { fill: T.card, r: 22, stroke: [T.border, 1], clip: false }); H.text(g1, 'Sign out of Tipsarr on this iPhone?', 16, 16, { size: 13, color: T.mutedFg, w: 345, align: 'center' }); H.rect(g1, 'divider', 0, 44, 377, 1, T.border); H.text(g1, 'Sign out', 0, 62, { size: 18, weight: 500, color: T.destructive, w: 377, align: 'center' }); const g2 = H.board(b, 'cancel', 8, 852 - 34 - 56, 377, 56, { fill: T.card, r: 22, stroke: [T.border, 1], clip: false }); H.text(g2, 'Cancel', 0, 16, { size: 18, weight: 600, color: T.fg, w: 377, align: 'center' }); return b; }],
  ['Change picture', (T, x, y) => { const b = C.screen(T, `Change picture · ${T.name}`, x, y); S.navBar(b, T, 'Settings'); const s = C.sheet(b, T, 360, 'Profile picture'); C.group(s, T, 20, 76, 353, [{ title: 'Choose from library', icon: 'image' }, { title: 'Remove my picture', icon: 'trash-2', danger: true, chev: false }]); H.text(s, 'Pictures are shared with other people on this server. Max 4 MB.', 24, 200, { size: 13, color: T.mutedFg, w: 345, lh: 1.35 }); return b; }],
];
