const H = storage.H, C = storage.C, S = storage.S;
const accounts = [['Alice', 'Admin  ·  tipsarr.brebond.com', 3, true], ['Bob', 'tipsarr.brebond.com', 2, false], ['Alice', 'tipsarr.friends.net', 5, false]];
C.accountRow = (p, T, x, y, w, a, o = {}) => { const [n, sub, ci, cur] = a; C.avatarSm(p, T, x, y + 8, n, ci, 44); H.text(p, n, x + 58, y + 8, { size: 17, weight: 600, color: T.fg }); H.text(p, sub, x + 58, y + 30, { size: 13, color: T.mutedFg, w: w - 58 - 40 }); if (cur) H.icon(p, 'check', x + w - 26, y + 17, 22, T.fg, 2.4); else if (o.remove) H.icon(p, 'x', x + w - 26, y + 18, 20, T.mutedFg, 2); };
S.accountsList = [
  ['Accounts · switcher', (T, x, y) => { const b = C.screen(T, `Accounts · switcher · ${T.name}`, x, y); C.largeTitle(b, T, 'Profile', { y: 62, right: ['settings', 'users'] }); const pal = C.pal[3]; H.ellipse(b, 'avatar', 393 / 2 - 44, 118, 88, 88, [H.grad([[pal[0], 0], [pal[1], 1]])]); H.text(b, 'A', 393 / 2 - 44, 140, { size: 36, weight: 700, color: '#FFFFFF', w: 88, align: 'center' }); H.text(b, 'Alice', 0, 220, { size: 26, weight: 700, color: T.fg, w: 393, align: 'center' });
    const s = C.sheet(b, T, 470, 'Accounts'); accounts.forEach((a, i) => { C.accountRow(s, T, 20, 76 + i * 64, 353, a); H.rect(s, 'divider', 78, 76 + i * 64 + 62, 295, 1, T.border); });
    C.btn(s, T, 20, 76 + 3 * 64 + 12, 353, 'Add account', { icon: 'plus', h: 50, v: 'secondary' }); H.text(s, 'Manage accounts', 0, 76 + 3 * 64 + 82, { size: 16, weight: 500, color: T.fg, w: 393, align: 'center' }); return b; }],
  ['Accounts · manage', (T, x, y) => { const b = C.screen(T, `Accounts · manage · ${T.name}`, x, y); S.navBar(b, T, 'Accounts'); H.text(b, 'Each account keeps its own sign-in on this iPhone. Switching is instant, no password needed.', 16, 106, { size: 14, color: T.mutedFg, w: 361, lh: 1.35 });
    const g = H.board(b, 'accounts', 16, 166, 361, 3 * 72, { fill: T.card, r: 16, clip: true, stroke: [T.border, 1] }); accounts.forEach((a, i) => { C.accountRow(g, T, 12, i * 72 + 4, 337, a, { remove: true }); if (i < 2) H.rect(g, 'divider', 70, i * 72 + 71, 291, 1, T.border); });
    C.btn(b, T, 16, 406, 361, 'Add account', { icon: 'plus', h: 50 }); H.text(b, 'Signing out removes an account from this iPhone. Face ID protects all accounts.', 24, 474, { size: 13, color: T.mutedFg, w: 345, lh: 1.35 }); C.homeIndicator(b, T); return b; }],
  ['Accounts · add', (T, x, y) => { const b = C.screen(T, `Accounts · add · ${T.name}`, x, y); S.navBar(b, T, 'Add account'); H.text(b, 'Server', 20, 110, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 });
    const g = H.board(b, 'servers', 16, 134, 361, 120, { fill: T.card, r: 16, clip: true, stroke: [T.border, 1] }); C.row(g, T, 0, 0, 361, { title: 'tipsarr.brebond.com', sub: 'Current server', icon: 'server', chev: false, card: false }); H.icon(g, 'check', 361 - 38, 21, 22, T.fg, 2.4); H.rect(g, 'divider', 60, 63, 301, 1, T.border); C.row(g, T, 0, 64, 361, { title: 'Another server…', icon: 'globe', card: false });
    C.field(b, T, 16, 282, 361, 'Username', { value: '', placeholder: 'Username', icon: 'user', focus: true }); C.field(b, T, 16, 372, 361, 'Password', { placeholder: 'Password', icon: 'key-round' }); C.btn(b, T, 16, 480, 361, 'Sign in', { h: 52, disabled: true }); C.homeIndicator(b, T); return b; }],
  ['Accounts · switching', (T, x, y) => { const b = C.screen(T, `Accounts · switching · ${T.name}`, x, y); C.avatarSm(b, T, 393 / 2 - 44, 330, 'Bob', 2, 88); H.text(b, 'Switching to Bob…', 0, 440, { size: 20, weight: 700, color: T.fg, w: 393, align: 'center' }); H.text(b, 'tipsarr.brebond.com', 0, 472, { size: 14, color: T.mutedFg, w: 393, align: 'center' }); H.icon(b, 'circle-dashed', 393 / 2 - 14, 510, 28, T.mutedFg, 2); C.homeIndicator(b, T); return b; }],
];
S.profileList = S.profileList.concat(S.accountsList);
