const H = storage.H, C = storage.C, S = storage.S;
const typeStyle = { video: ['#6366F1', 'film'], audio: ['#0EA5E9', 'volume-2'], subtitles: ['#F59E0B', 'message-square'], other: ['#737373', 'info'] };
C.issueRow = (p, T, x, y, w, title, type, who, when, comments, resolved) => {
  const [col, ic] = typeStyle[type]; const ib = H.board(p, 'type ' + type, x, y + 4, 44, 44, { fill: col, op: 0.16, r: 12, clip: false }); H.icon(ib, ic, 10, 10, 24, col, 2);
  H.text(p, title, x + 58, y + 2, { size: 16, weight: 600, color: T.fg, w: w - 58 - 70 });
  H.text(p, `${type[0].toUpperCase() + type.slice(1)}  ·  ${who}  ·  ${when}`, x + 58, y + 26, { size: 13, color: T.mutedFg, w: w - 58 });
  if (comments) { const cb = H.board(p, 'comments', x + w - 46, y + 4, 46, 22, { fill: T.muted, r: 11, clip: false }); H.icon(cb, 'message-square', 8, 4, 14, T.mutedFg, 2); H.text(cb, String(comments), 26, 3, { size: 12, weight: 600, color: T.fg }); }
  if (resolved) { const rb2 = H.board(p, 'resolved', x + 58, y + 52, 64, 20, { fill: '#10B981', op: 0.16, r: 10, clip: false }); H.text(rb2, 'Resolved', 0, 3, { size: 11, weight: 600, color: '#10B981', w: 64, align: 'center' }); } else { const ob = H.board(p, 'open', x + 58, y + 52, 52, 20, { fill: '#F43F5E', op: 0.16, r: 10, clip: false }); H.text(ob, 'Open', 0, 3, { size: 11, weight: 600, color: '#F43F5E', w: 52, align: 'center' }); }
};
const bubble = (p, T, x, y, w, who, text, mine, when, ci) => { const pal = C.pal[ci % 12]; const lines = Math.ceil(text.length / 34); const h = 20 + lines * 20; const bx = mine ? 393 - 16 - w : 16 + 36; const b = H.board(p, 'message', bx, y + 20, w, h, { fill: mine ? T.primary : T.muted, r: 18, clip: false }); H.text(b, text, 14, 10, { size: 15, color: mine ? T.primaryFg : T.fg, w: w - 28, lh: 1.3 }); if (!mine) C.avatarSm(p, T, 16, y + 20 + h - 28, who, ci, 28); H.text(p, `${who}  ·  ${when}`, bx + 4, y, { size: 11, color: T.mutedFg, w: w - 8, align: mine ? 'right' : 'left' }); return h + 36; };
S.adminList = [
  ['Profile · admin', (T, x, y) => { const b = C.screen(T, `Profile · admin · ${T.name}`, x, y); C.largeTitle(b, T, 'Profile', { y: 62, right: ['settings', 'users'] }); const pal = C.pal[3]; H.ellipse(b, 'avatar', 393 / 2 - 36, 114, 72, 72, [H.grad([[pal[0], 0], [pal[1], 1]])]); H.text(b, 'A', 393 / 2 - 36, 134, { size: 30, weight: 700, color: '#FFFFFF', w: 72, align: 'center' }); H.text(b, 'Alice', 0, 198, { size: 24, weight: 700, color: T.fg, w: 393, align: 'center' }); const ab = H.board(b, 'admin badge', 393 / 2 - 28, 230, 56, 22, { fill: T.primary, r: 11, clip: false }); H.text(ab, 'Admin', 0, 4, { size: 12, weight: 600, color: T.primaryFg, w: 56, align: 'center' });
    C.stat(b, T, 16, 272, 112, 'Requests', '12', 'list-checks'); C.stat(b, T, 140, 272, 112, 'Watchlist', '8', 'bookmark'); C.stat(b, T, 264, 272, 113, 'Watched', '143', 'eye');
    H.text(b, 'ADMINISTRATION', 20, 372, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.group(b, T, 16, 394, 361, [{ title: 'Pending requests', icon: 'clock', value: '3', iconBg: '#F59E0B', iconBgOp: 0.16, iconColor: '#F59E0B' }, { title: 'Issues', icon: 'flag', value: '2 open', iconBg: '#F43F5E', iconBgOp: 0.16, iconColor: '#F43F5E' }, { title: 'Users', icon: 'users', value: '6' }, { title: 'Sync & jobs', icon: 'refresh-cw' }, { title: 'Stats', icon: 'chart-no-axes-column' }]);
    C.finish(b, T, { tab: 4 }); return b; }],
  ['Issues · list', (T, x, y) => { const b = C.screen(T, `Issues · list · ${T.name}`, x, y); S.navBar(b, T, 'Issues'); C.segmented(b, T, 16, 108, 361, ['Open (2)', 'Resolved', 'All'], 0);
    [['Dune: Part Two', 'video', 'Bob', '2h', 3, false], ['Severance S2E4', 'subtitles', 'Carol', 'yesterday', 1, false], ['Silo', 'audio', 'Dan', '3 days', 4, true], ['Fallout', 'other', 'Bob', '1 week', 2, true]].forEach((r, k) => { C.issueRow(b, T, 16, 168 + k * 104, 361, ...r); H.rect(b, 'divider', 74, 168 + k * 104 + 90, 303, 1, T.border); });
    C.homeIndicator(b, T); return b; }],
  ['Issue · detail', (T, x, y) => { const b = C.screen(T, `Issue · detail · ${T.name}`, x, y); S.navBar(b, T, 'Issue', { right: 'Resolve' });
    C.poster(b, T, 16, 108, 56, 0, { badge: false, noTitle: true, noIcon: true, r: 8 }); H.text(b, 'Dune: Part Two', 88, 112, { size: 17, weight: 700, color: T.fg }); const [col] = typeStyle.video; const tb = H.board(b, 'type', 88, 140, 70, 22, { fill: col, op: 0.16, r: 11, clip: false }); H.text(tb, 'Video', 0, 4, { size: 12, weight: 600, color: col, w: 70, align: 'center' });
    H.text(b, 'Comments', 16, 190, { size: 18, weight: 700, color: T.fg });
    [['Bob', '2h ago', 'The picture freezes around 1h20 in the desert scene, audio keeps going.', 2], ['Alice', '1h ago', 'Thanks, I’ll re-download it in a better quality profile.', 0], ['Bob', '40m ago', 'Great, I’ll check tonight.', 2]].forEach(([who, when, text, ci], k) => { const yy = 228 + k * 104; C.avatarSm(b, T, 16, yy, who, ci, 32); H.text(b, who, 60, yy, { size: 15, weight: 600, color: T.fg }); H.text(b, when, 60, yy + 20, { size: 12, color: T.mutedFg }); H.text(b, text, 60, yy + 40, { size: 15, color: T.fg, w: 317, lh: 1.3, op: 0.9 }); H.rect(b, 'divider', 16, yy + 92, 361, 1, T.border); });
    const ta = H.board(b, 'reply field', 16, 560, 361, 96, { fill: T.muted, r: 14, clip: false }); H.text(ta, 'Write a comment…', 14, 12, { size: 16, color: T.mutedFg }); C.btn(b, T, 16, 668, 361, 'Comment', { h: 46, icon: 'message-square' });
    C.homeIndicator(b, T); return b; }],
  ['Users · list', (T, x, y) => { const b = C.screen(T, `Users · list · ${T.name}`, x, y); S.navBar(b, T, 'Users');
    [['Alice', 'Admin', 'today', 0], ['Bob', 'User', 'today', 2], ['Carol', 'User', 'yesterday', 4], ['Dan', 'User', '3 days ago', 6], ['Erin', 'User', '2 weeks ago', 8]].forEach(([n, r, w, ci], k) => { const yy = 112 + k * 80; C.avatarSm(b, T, 16, yy + 8, n, ci, 48); H.text(b, n, 80, yy + 8, { size: 16, weight: 600, color: T.fg }); H.text(b, `Last seen ${w}`, 80, yy + 30, { size: 13, color: T.mutedFg }); const rb = H.board(b, 'role', 393 - 16 - 20 - 56, yy + 18, 56, 24, { fill: r === 'Admin' ? T.primary : T.muted, r: 12, clip: false }); H.text(rb, r, 0, 5, { size: 12, weight: 600, color: r === 'Admin' ? T.primaryFg : T.fg, w: 56, align: 'center' }); H.icon(b, 'chevron-right', 353, yy + 20, 20, T.mutedFg, 2); H.rect(b, 'divider', 80, yy + 70, 297, 1, T.border); }); C.homeIndicator(b, T); return b; }],
  ['User · detail', (T, x, y) => { const b = C.screen(T, `User · detail · ${T.name}`, x, y); S.navBar(b, T, 'Bob'); C.avatarSm(b, T, 393 / 2 - 44, 112, 'Bob', 2, 88); H.text(b, 'Bob', 0, 214, { size: 24, weight: 700, color: T.fg, w: 393, align: 'center' }); H.text(b, 'Jellyfin user  ·  member since Nov 2025', 0, 246, { size: 13, color: T.mutedFg, w: 393, align: 'center' });
    H.text(b, 'ROLE', 20, 290, { size: 12, weight: 600, color: T.mutedFg, ls: 0.5 }); C.segmented(b, T, 16, 312, 361, ['User', 'Admin'], 0);
    C.group(b, T, 16, 372, 361, [{ title: 'Language', value: 'Français', chev: false }, { title: 'Region', value: 'FR', chev: false }, { title: 'Requests', value: '9', chev: true }, { title: 'Signed-in devices', value: '2', chev: true }]);
    C.btn(b, T, 16, 640, 361, 'Sign out everywhere', { h: 48, v: 'secondary', icon: 'log-out' }); C.homeIndicator(b, T); return b; }],
  ['Sync & jobs', (T, x, y) => { const b = C.screen(T, `Sync and jobs · ${T.name}`, x, y); S.navBar(b, T, 'Sync & jobs');
    [['Library sync', 'ok', '485 titles · 2h ago'], ['History sync', 'ok', '1,434 plays · 2h ago'], ['Playback sync', 'run', 'running…'], ['Suggestions refresh', 'ok', 'daily · 6h ago'], ['Box office', 'fail', 'failed · 1 day ago']].forEach(([n, st, sub], k) => { const yy = 112 + k * 92; const card = H.board(b, 'job ' + n, 16, yy, 361, 80, { fill: T.card, r: 16, stroke: [T.border, 1], clip: false }); const col = st === 'ok' ? '#10B981' : st === 'run' ? '#6366F1' : '#EA580C'; const ib = H.board(card, 'status', 14, 20, 40, 40, { fill: col, op: 0.16, r: 12, clip: false }); H.icon(ib, st === 'ok' ? 'check' : st === 'run' ? 'refresh-cw' : 'triangle-alert', 10, 10, 20, col, 2.2); H.text(card, n, 68, 16, { size: 16, weight: 600, color: T.fg }); H.text(card, sub, 68, 40, { size: 13, color: T.mutedFg }); C.btn(card, T, 361 - 14 - 78, 22, 78, 'Run', { h: 34, size: 14, v: 'secondary' }); }); C.homeIndicator(b, T); return b; }],
  ['Stats', (T, x, y) => { const b = C.screen(T, `Stats · ${T.name}`, x, y); S.navBar(b, T, 'Stats');
    C.stat(b, T, 16, 108, 112, 'Plays', '1,434', 'play'); C.stat(b, T, 140, 108, 112, 'Hours', '2,310', 'clock'); C.stat(b, T, 264, 108, 113, 'Users', '6', 'users');
    H.text(b, 'Plays per week', 16, 208, { size: 20, weight: 700, color: T.fg }); const vals = [22, 31, 18, 40, 52, 36, 44, 61, 38, 49, 66, 54]; vals.forEach((v, i) => H.rect(b, 'bar', 20 + i * 29.5, 464 - v * 3, 20, v * 3, i === 10 ? T.fg : T.muted, { r: 5 })); H.rect(b, 'axis', 16, 466, 361, 1, T.border);
    H.text(b, 'Most watched', 16, 500, { size: 20, weight: 700, color: T.fg }); [[0, 38], [3, 31], [5, 24]].forEach(([n, c], k) => { const yy = 540 + k * 68; C.poster(b, T, 16, yy, 40, n, { badge: false, noTitle: true, noIcon: true, r: 6 }); H.text(b, C.items[n].t, 70, yy + 8, { size: 16, weight: 600, color: T.fg }); H.text(b, `${c} plays`, 70, yy + 32, { size: 13, color: T.mutedFg }); }); C.homeIndicator(b, T); return b; }],
];
