const H = storage.H, C = storage.C, S = storage.S, P = S.P;
// iPhone Duo (Apple foldable), sizes from Apple's tech talk "Designing apps for iPhone Duo": outer 466x678 pt, inner 626x890 pt (inner is regular x regular, ignores orientation).
const D = S.D = {};
D.board = (T, name, x, y, w, h) => { const b = H.board(null, name, x, y, w, h, { fill: T.bg, r: 28 }); P.statusBar(b, T, w); return b; };
D.fold = (b, T, x, y, w, h, label) => { const f = H.rect(b, 'fold (device hinge)', x, y, w, h, T.isDark ? '#FFFFFF' : '#000000', { op: 0.06 }); if (label) H.text(b, label, x, y + h / 2 - 8, { size: 11, weight: 600, color: T.mutedFg, w: w, align: 'center', name: 'fold label' }); return f; };
D.tabs = (b, T, x, y, w, active, compact) => { const tb = H.board(b, 'tab bar', x, y, w, compact ? 52 : 62, { fill: T.card, r: 31, stroke: [T.border, 1], clip: false }); ['compass', 'search', 'list-checks', 'library', 'user'].forEach((ic, i) => { const cw = w / 5; if (i === active) H.rect(tb, 'active', i * cw + 6, 5, cw - 12, (compact ? 52 : 62) - 10, T.muted, { r: 26 }); H.icon(tb, ic, i * cw + (cw - 22) / 2, compact ? 14 : 18, 22, i === active ? T.fg : T.mutedFg, 2); }); };
D.rail = (b, T, x, y, h) => { const w = 72; const r = H.board(b, 'sidebar (collapsed)', x, y, w, h, { fill: T.isDark ? '#101010' : '#F7F7F8', clip: true }); H.rect(r, 'edge', w - 1, 0, 1, h, T.border); C.appIcon(r, 18, 44, 36, T.isDark ? 'Dark' : 'Light'); ['compass', 'search', 'list-checks', 'library', 'user'].forEach((ic, i) => { if (i === 0) H.rect(r, 'active', 10, 108 + i * 52, 52, 44, T.muted, { r: 12 }); H.icon(r, ic, 25, 119 + i * 52, 22, i === 0 ? T.fg : T.mutedFg, 2); }); return w; };
D.grid = (b, T, x, y, cols, pw, gap, n, from = 0) => { for (let i = 0; i < n; i++) { const col = i % cols, row = Math.floor(i / cols); const px = x + col * (pw + gap), py = y + row * (Math.round(pw * 1.5) + 48); C.poster(b, T, px, py, pw, i + from); const it = C.items[(i + from) % 12]; H.text(b, it.t, px, py + Math.round(pw * 1.5) + 6, { size: 13, weight: 600, color: T.fg, w: pw }); H.text(b, `${it.y} · ${it.k === 'tv' ? 'TV' : 'Movie'}`, px, py + Math.round(pw * 1.5) + 24, { size: 12, color: T.mutedFg, w: pw }); } };
D.detail = (b, T, x, y, w, o = {}) => { const pal = C.pal[0]; H.board(b, 'backdrop', x, y, w, 250, { fill: [H.grad([[pal[0], 0], [pal[1], 0.8], [T.bg, 1]])], clip: true });
  C.poster(b, T, x + 20, y + 120, 110, 0, { badge: false, noTitle: true, r: 12 }); const narrow = w < 420; H.text(b, 'Dune: Part Two', x + 146, y + 134, { size: narrow ? 20 : 24, weight: 700, color: '#FFFFFF', w: w - 166 }); H.text(b, '2024  ·  2h 46m  ·  PG-13', x + 146, y + (narrow ? 196 : 170), { size: 13, color: '#D4D4D8' }); C.badge(b, T, x + 146, y + (narrow ? 222 : 196), 'available', {});
  C.ratingsStrip(b, T, x + 20, y + 296, w - 40, 'movie'); if (!o.noActions) { C.btn(b, T, x + 20, y + 356, w - 40 - 58, 'Open in Jellyfin', { icon: 'play', v: 'success', h: 48 }); const mb = H.board(b, 'menu', x + w - 20 - 48, y + 356, 48, 48, { fill: T.muted, r: 24, clip: false }); H.icon(mb, 'ellipsis', 12, 12, 24, T.fg, 2); }
  if (!o.short) { H.text(b, 'Overview', x + 20, y + 428, { size: 20, weight: 700, color: T.fg }); H.text(b, 'Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.', x + 20, y + 462, { size: 15, color: T.fg, w: w - 40, lh: 1.4, op: 0.85 }); } };
S.duoList = [
  ['Outer · portrait · Discover (466×678)', (T, x, y) => { const b = D.board(T, `Foldable outer portrait · Discover · ${T.name}`, x, y, 466, 678); H.text(b, 'Discover', 20, 40, { size: 34, weight: 700, color: T.fg, ls: -0.4 }); let cx = 20; [['Trending', true], ['Upcoming', false], ['Movies', false], ['TV', false]].forEach(([l, a]) => { const c = C.chip(b, T, cx, 92, l, { active: a }); cx += c.width + 8; }); D.grid(b, T, 20, 142, 3, 134, 12, 3); H.text(b, 'Suggested for you', 20, 400, { size: 20, weight: 700, color: T.fg }); D.grid(b, T, 20, 436, 3, 134, 12, 3, 3); D.tabs(b, T, 16, 678 - 16 - 62, 434, 0, false); return b; }],
  ['Outer · portrait · Detail', (T, x, y) => { const b = D.board(T, `Foldable outer portrait · Detail · ${T.name}`, x, y, 466, 678); D.detail(b, T, 0, 0, 466, { short: false }); return b; }],
  ['Outer · landscape · Discover (678×466)', (T, x, y) => { const b = D.board(T, `Foldable outer landscape · Discover · ${T.name}`, x, y, 678, 466); H.text(b, 'Trending now', 24, 36, { size: 20, weight: 700, color: T.fg }); for (let i = 0; i < 5; i++) C.poster(b, T, 24 + i * 128, 72, 116, i + 1); D.tabs(b, T, 24, 466 - 12 - 52, 630, 0, true); return b; }],
  ['Inner · portrait · Discover (626×890)', (T, x, y) => { const b = D.board(T, `Foldable inner portrait · Discover · ${T.name}`, x, y, 626, 890); const rw = D.rail(b, T, 0, 0, 890); H.text(b, 'Discover', rw + 24, 44, { size: 34, weight: 700, color: T.fg, ls: -0.4 }); let cx = rw + 24; [['Trending', true], ['Upcoming', false], ['Movies', false], ['TV', false]].forEach(([l, a]) => { const c = C.chip(b, T, cx, 98, l, { active: a }); cx += c.width + 8; }); D.grid(b, T, rw + 24, 152, 4, 118, 12, 8); P.statusBar(b, T, 626); return b; }],
  ['Inner · portrait · Search + detail', (T, x, y) => { const b = D.board(T, `Foldable inner portrait · Search and detail · ${T.name}`, x, y, 626, 890); const rw = D.rail(b, T, 0, 0, 890); const lw = 250; H.rect(b, 'pane edge', rw + lw, 0, 1, 890, T.border); C.search(b, T, rw + 12, 48, lw - 24, 'Search', { value: 'dune' }); [0, 9, 3, 5, 11, 7].forEach((n, k) => { const yy = 112 + k * 112; if (k === 0) H.rect(b, 'selected', rw + 4, yy - 8, lw - 8, 106, T.muted, { r: 12 }); C.poster(b, T, rw + 14, yy, 56, n, { noTitle: true, noIcon: true, badge: false, r: 8 }); H.text(b, C.items[n].t, rw + 80, yy + 2, { size: 15, weight: 600, color: T.fg, w: lw - 92 }); H.text(b, `${C.items[n].y} · ${C.items[n].k === 'tv' ? 'TV' : 'Movie'}`, rw + 80, yy + 24, { size: 12, color: T.mutedFg }); if (C.items[n].s) C.badge(b, T, rw + 80, yy + 50, C.items[n].s, { h: 20 }); }); D.detail(b, T, rw + lw + 1, 0, 626 - rw - lw - 1, {}); P.statusBar(b, T, 626); return b; }],
  ['Inner · landscape · three panes (890×626)', (T, x, y) => { const b = D.board(T, `Foldable inner landscape · three panes · ${T.name}`, x, y, 890, 626); const rw = D.rail(b, T, 0, 0, 626); const lw = 290; H.rect(b, 'pane edge', rw + lw, 0, 1, 626, T.border); H.text(b, 'Requests', rw + 20, 40, { size: 26, weight: 700, color: T.fg }); [[1, 'requested'], [3, 'downloading'], [0, 'available'], [8, 'declined']].forEach(([i, s], k) => { const yy = 96 + k * 108; if (k === 1) H.rect(b, 'selected', rw + 6, yy - 8, lw - 12, 102, T.muted, { r: 12 }); C.requestRow(b, T, rw + 16, yy, lw - 32, i, { status: s, when: '3 days ago' }); });
    const dx = rw + lw + 1; H.text(b, 'Severance', dx + 28, 44, { size: 28, weight: 700, color: T.fg }); H.text(b, '2022  ·  TV show', dx + 28, 82, { size: 14, color: T.mutedFg }); C.badge(b, T, dx + 28, 108, 'downloading', {}); C.progress(b, T, dx + 28, 150, 340, 0.62); H.text(b, '62%  ·  about 12 min left', dx + 28, 164, { size: 13, color: T.mutedFg }); H.text(b, 'Progress', dx + 28, 210, { size: 20, weight: 700, color: T.fg }); C.timeline(b, T, dx + 32, 254, [['Requested', 'Mar 3, 18:02'], ['Approved', 'by Alice'], ['Searching', 'sent to Sonarr · Mar 3, 18:05'], ['Downloading', 'in progress'], ['Available', ' ']], 3); P.statusBar(b, T, 890); return b; }],
  ['Split View · Tipsarr + another app', (T, x, y) => { const b = D.board(T, `Foldable split view · ${T.name}`, x, y, 626, 890); H.text(b, 'Discover', 16, 44, { size: 28, weight: 700, color: T.fg, ls: -0.3 }); let cx = 16; [['Trending', true], ['Upcoming', false]].forEach(([l, a]) => { const c = C.chip(b, T, cx, 90, l, { active: a }); cx += c.width + 8; }); D.grid(b, T, 16, 140, 2, 138, 14, 4); D.tabs(b, T, 12, 890 - 16 - 56, 289, 0, true); D.fold(b, T, 306, 0, 14, 890, null); const o = H.rect(b, 'other app', 320, 0, 306, 890, T.isDark ? '#1C1C1E' : '#EFEFF1', {}); H.text(b, 'Another app', 320, 400, { size: 15, weight: 600, color: T.mutedFg, w: 306, align: 'center' }); H.text(b, 'Two windows of 313 pt each. Tipsarr runs with the compact layout in one of them.', 340, 424, { size: 12, color: T.mutedFg, w: 266, align: 'center' }); return b; }],
  ['Partially folded · laptop posture', (T, x, y) => { const b = D.board(T, `Foldable laptop posture · ${T.name}`, x, y, 890, 626); const pal = C.pal[0]; H.board(b, 'top half', 0, 0, 890, 313, { fill: [H.grad([[pal[0], 0], [pal[1], 0.8], [T.bg, 1]])], clip: true }); C.poster(b, T, 32, 80, 150, 0, { badge: false, noTitle: true, r: 12 }); H.text(b, 'Dune: Part Two', 206, 100, { size: 34, weight: 700, color: '#FFFFFF' }); H.text(b, '2024  ·  2h 46m  ·  PG-13', 206, 146, { size: 15, color: '#D4D4D8' }); C.badge(b, T, 206, 182, 'available', {}); P.statusBar(b, T, 890);
    D.fold(b, T, 0, 295, 890, 36, 'Fold: content above, controls below, nothing tappable on the hinge');
    C.ratingsStrip(b, T, 32, 360, 826, 'movie'); C.btn(b, T, 32, 430, 400, 'Open in Jellyfin', { icon: 'play', v: 'success', h: 52 }); C.btn(b, T, 448, 430, 200, 'Add to watchlist', { icon: 'bookmark', v: 'secondary', h: 52 }); C.btn(b, T, 664, 430, 194, 'Report an issue', { icon: 'flag', v: 'secondary', h: 52 }); H.text(b, 'Controls move to the lower half when the device is partly folded.', 32, 510, { size: 13, color: T.mutedFg }); return b; }],
];
