const H = storage.H, C = storage.C, S = storage.S, P = S.P;
const duoBase = (T, name, x, y) => { const b = H.board(null, name, x, y, 840, 900, { fill: T.bg, r: 0 }); P.statusBar(b, T, 840); H.rect(b, 'hinge', 419, 0, 2, 900, T.border); return b; };
const duoTabs = (b, T, active) => { const lw = 420; const tb = H.board(b, 'tab bar', 20, 900 - 20 - 60, lw - 40, 60, { fill: T.card, r: 30, stroke: [T.border, 1], clip: false }); ['compass', 'search', 'list-checks', 'library', 'user'].forEach((ic, i) => { const w = (lw - 40) / 5; if (i === active) H.rect(tb, 'active', i * w + 6, 6, w - 12, 48, T.muted, { r: 24 }); H.icon(tb, ic, i * w + (w - 24) / 2, 18, 24, i === active ? T.fg : T.mutedFg, 2); }); };
S.duoList = [
  ['Foldable inner · Discover + detail', P.duo],
  ['Foldable inner · Requests', (T, x, y) => { const b = duoBase(T, `Foldable inner · Requests · ${T.name}`, x, y); H.text(b, 'Requests', 20, 48, { size: 30, weight: 700, color: T.fg }); let cx = 20; ['All', 'Pending', 'Approved'].forEach((l, i) => { const c = C.chip(b, T, cx, 96, l, { active: i === 0 }); cx += c.width + 8; });
    [[1, 'requested', '2 days ago'], [3, 'downloading', '3 days ago'], [0, 'available', '1 week ago'], [8, 'declined', '2 weeks ago']].forEach(([i, s, w], k) => { const yy = 152 + k * 116; if (k === 1) H.rect(b, 'selected', 8, yy - 8, 404, 112, T.muted, { r: 14 }); C.requestRow(b, T, 20, yy, 380, i, { status: s, when: w }); }); duoTabs(b, T, 2);
    const dx = 440; H.text(b, 'Severance', dx, 64, { size: 28, weight: 700, color: T.fg }); H.text(b, '2022  ·  TV show', dx, 102, { size: 14, color: T.mutedFg }); C.badge(b, T, dx, 130, 'downloading', {}); C.progress(b, T, dx, 174, 360, 0.62); H.text(b, '62%  ·  about 12 min left', dx, 190, { size: 13, color: T.mutedFg });
    H.text(b, 'Progress', dx, 240, { size: 20, weight: 700, color: T.fg }); C.timeline(b, T, dx + 4, 284, [['Requested', 'Mar 3, 18:02'], ['Approved', 'Mar 3, 18:05'], ['Searching', 'Mar 3, 18:05'], ['Downloading', 'in progress'], ['Available', 'waiting']], 3); C.btn(b, T, dx, 800, 360, 'Cancel request', { v: 'secondary', h: 46 }); return b; }],
  ['Foldable inner · Library', (T, x, y) => { const b = duoBase(T, `Foldable inner · Library · ${T.name}`, x, y); H.text(b, 'Library', 20, 48, { size: 30, weight: 700, color: T.fg }); let cx = 20; ['All', 'Movies', 'TV'].forEach((l, i) => { const c = C.chip(b, T, cx, 96, l, { active: i === 0 }); cx += c.width + 8; });
    for (let i = 0; i < 6; i++) { const col = i % 3, row = Math.floor(i / 3); const pw = 118; const px = 20 + col * (pw + 12), py = 150 + row * 228; C.poster(b, T, px, py, pw, i, { badge: false }); H.text(b, C.items[i].t, px, py + 182, { size: 13, weight: 600, color: T.fg, w: pw }); H.text(b, C.items[i].y, px, py + 200, { size: 12, color: T.mutedFg }); } duoTabs(b, T, 3);
    const dx = 440; H.text(b, 'Filters', dx, 56, { size: 24, weight: 700, color: T.fg }); H.text(b, 'Genre', dx, 112, { size: 15, weight: 600, color: T.fg }); let gx = dx, gy = 144; [['Action', 0], ['Comedy', 0], ['Drama', 1], ['Sci-Fi', 1], ['Thriller', 0]].forEach(([g, a]) => { const c = C.chip(b, T, gx, gy, g, { active: !!a }); gx += c.width + 8; if (gx > 780) { gx = dx; gy += 42; } });
    H.text(b, 'Watched', dx, 236, { size: 15, weight: 600, color: T.fg }); C.segmented(b, T, dx, 268, 360, ['Any', 'Watched', 'Not watched'], 0); H.text(b, 'Minimum rating', dx, 330, { size: 15, weight: 600, color: T.fg }); H.rect(b, 'track', dx, 372, 360, 4, T.muted, { r: 2 }); H.rect(b, 'range', dx, 372, 240, 4, T.fg, { r: 2 }); H.ellipse(b, 'thumb', dx + 230, 364, 20, 20, T.bg, { stroke: [T.fg, 2] }); C.btn(b, T, dx, 800, 360, 'Show 142 titles', { h: 48 }); return b; }],
];
