// Generates platform code from design/tokens.json. Run: node design/build-tokens.mjs
// Outputs design/generated/Tokens.swift (iOS). Android (Theme.kt) is generated the same way when that app starts.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(fs.readFileSync(path.join(here, 'tokens.json'), 'utf8'));
const out = path.join(here, 'generated');
fs.mkdirSync(out, { recursive: true });

const HEX = /^#([0-9A-Fa-f]{6})([0-9A-Fa-f]{2})?$/;
const entries = (group) => Object.entries(group).filter(([k]) => !k.startsWith('$'));
const val = (t) => t.$value;
const fail = (m) => { console.error('tokens.json: ' + m); process.exit(1); };

for (const mode of ['light', 'dark']) for (const [k, t] of entries(tokens.color[mode])) if (!HEX.test(val(t))) fail(`color.${mode}.${k} is not a hex colour: ${val(t)}`);
const lightKeys = entries(tokens.color.light).map(([k]) => k).sort().join();
const darkKeys = entries(tokens.color.dark).map(([k]) => k).sort().join();
if (lightKeys !== darkKeys) fail('light and dark palettes must define the same keys');
for (const [k, t] of entries(tokens.color.status)) if (!HEX.test(val(t))) fail(`color.status.${k} is not a hex colour`);

const swiftName = (k) => k.replace(/^(\d)/, '_$1').replace(/-(\w)/g, (_, c) => c.toUpperCase());
const hexLiteral = (h) => { const m = HEX.exec(h); return `0x${m[1].toUpperCase()}${(m[2] || 'FF').toUpperCase()}`; };

let s = `// Generated by design/build-tokens.mjs from design/tokens.json. Do not edit by hand.
import SwiftUI
import UIKit

public enum Tokens {
    /// Neutral colours that change with light / dark mode.
    public struct Palette: Sendable {
${entries(tokens.color.light).map(([k]) => `        public let ${swiftName(k)}: Color`).join('\n')}
    }

    public static let palette = Palette(
${entries(tokens.color.light).map(([k, t], i, a) => `        ${swiftName(k)}: Color.dynamic(light: ${hexLiteral(val(t))}, dark: ${hexLiteral(val(tokens.color.dark[k]))})${i < a.length - 1 ? ',' : ''}`).join('\n')}
    )

    /// One colour per request / availability state, same in both modes.
    public enum Status {
${entries(tokens.color.status).map(([k, t]) => `        public static let ${swiftName(k)} = Color(hex: ${hexLiteral(val(t))})`).join('\n')}
    }

    public enum Spacing {
${entries(tokens.spacing).map(([k, t]) => `        public static let ${swiftName(k)}: CGFloat = ${val(t)}`).join('\n')}
    }

    public enum Radius {
${entries(tokens.radius).map(([k, t]) => `        public static let ${swiftName(k)}: CGFloat = ${val(t)}`).join('\n')}
    }

    public enum FontSize {
${entries(tokens.fontSize).map(([k, t]) => `        public static let ${swiftName(k)}: CGFloat = ${val(t)}`).join('\n')}
    }

    public enum Size {
${entries(tokens.size).map(([k, t]) => `        public static let ${swiftName(k)}: CGFloat = ${val(t)}`).join('\n')}
    }

    public enum Motion {
${entries(tokens.motion).map(([k, t]) => `        public static let ${swiftName(k)}: Double = ${val(t)}`).join('\n')}
    }
}

extension Color {
    /// 0xRRGGBBAA
    public init(hex: UInt32) {
        let r = Double((hex >> 24) & 0xFF) / 255, g = Double((hex >> 16) & 0xFF) / 255
        let b = Double((hex >> 8) & 0xFF) / 255, a = Double(hex & 0xFF) / 255
        self.init(.sRGB, red: r, green: g, blue: b, opacity: a)
    }

    static func dynamic(light: UInt32, dark: UInt32) -> Color {
        Color(UIColor { $0.userInterfaceStyle == .dark ? UIColor(Color(hex: dark)) : UIColor(Color(hex: light)) })
    }
}
`;
fs.writeFileSync(path.join(out, 'Tokens.swift'), s);
console.log('wrote design/generated/Tokens.swift');
